[project]
name = "musicmatch"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "cryptography>=50.0.1",
    "flask>=3.1.3",
    "flask-cors>=6.0.5",
    "flask-jwt-extended>=4.7.4",
    "psycopg>=3.3.5",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "werkzeug>=3.1.8",
    "yandex-music>=3.0.0",
]
